version: '3'
services:
  service_dock:
    build:
      context: .
      dockerfile: DockerfileAPIDocker
    container_name: apiserver
    networks:
      - my_network

  service_call:
    build:
      context: .
      dockerfile: DockerfileAPICaller
    container_name: apicaller
    depends_on:
      - service_dock
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

